[package]
name = "rcore-step-by-step"
version = "0.1.0"
authors = ["Cao Dingyuan <2017011417@secoder.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
